### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by seadynamic8** [mprymek/bertgate#2]
In the README:

for the mix.exs dep include, it should be:
:bert_gate instead of :bertgate
Took me awhile to figure that out. (still learning Elixir)

Also, if you add a @moduledoc for your mix tasks, they would show up when you run `mix help`

Cool project by the way, first time I've used BERT-RPC.

**Comment by mprymek** [comment]
Thanks a lot!

Issues fixed in 2292c8e6692d3edd24639ce64abe0f630f73d5fb and 7e0d565932630ec4cb44972f3dca74af3a9b1b48

BTW, if you are interested in RPC, I'm working on RPC based on MQTT protocol. Will publish soon, stay tuned :)
