### ISSUE TITLE
Tag new versions?

### ISSUE THREAD

**Issue by mrleeio** [mprymek/bertgate#6]
Hello,

Thank you for your efforts in writing this library, would it be possible for you to tag your releases?

Your most recent jump to elixir 1.6 introduced a breaking change to a production app.  Although we are now using a commit sha I believe breaking changes are more easily communicated via semantic versioning.

Just a suggestion, thanks again 👍

**Comment by mprymek** [comment]
Ouch, I'm very sorry for that, thank you.

In fact, I didn't realize anybody is using Bertgate in production. If you have a minute, I would be very pleased if you could write me a short mail about what you are using Bergate for, what your experience with it is and whether I can make anything for you.

I will be more cautious in the future, I swear ;)

**Comment by mrleeio** [comment]
We used the BERT and BERT-RPC Specification as a transport layer between Ruby and Elixir micro services.  I'm not sure why they chose this library at the time it was implemented but it has worked flawlessly so far.

I'll go head and close this issue, no need for it to clutter your project.
